heat_template_version: 2016-10-14

description: >
  MySQL service deployment using puppet

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerMysqlImage:
    description: image
    default: 'centos-binary-mariadb:latest'
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json

    
resources:

  MysqlPuppetBase:
    type: ../../../puppet/services/database/mysql.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}

outputs:
  role_data:
    description: Containerized service MySQL using composable services.
    value:
      service_name: {get_attr: [MysqlPuppetBase, role_data, service_name]}
      config_settings: {get_attr: [MysqlPuppetBase, role_data, config_settings]}
      step_config: {get_attr: [MysqlPuppetBase, role_data, step_config]}
      upgrade_tasks: {get_attr: [MysqlPuppetBase, role_data, step_config]}
      # BEGIN DOCKER SETTINGS #
      docker_image: &mysql_image
        list_join:
          - '/'
          - [ {get_param: DockerNamespace}, {get_param: DockerMysqlImage} ]
      puppet_tags: file # set this even though file is the default
      config_volume: mysql
      config_image: *mysql_image
      kolla_config:
        /var/lib/kolla/config_files/mysql.json:
          command: /usr/bin/mysqld_safe
          config_files:
          - dest: /etc/mysql/my.cnf
            source: /var/lib/kolla/config_files/src/etc/my.cnf
            owner: mysql
            perm: '0600'
      docker_config:
        step_2:
          mysql_db_init:
            image: *mysql_image
            net: host
            privileged: false
            detach: false
            command:
              ['mysql_install_db']
            volumes: &mysql_volumes
              - /var/lib/kolla/config_files/mysql.json:/var/lib/kolla/config_files/config.json
              - /var/lib/config-data/mysql/:/var/lib/kolla/config_files/src:ro
              - /etc/localtime:/etc/localtime:ro
              - /lib/modules:/lib/modules:ro
              - /run:/run
              - /dev:/dev
              - logs:/var/log/kolla/
              - mariadb:/var/lib/mysql/
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
          mysql:
            image: *mysql_image
            net: host
            privileged: false
            volumes: *mysql_volumes
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
