heat_template_version: ocata

description: >
  OpenStack Neutron openvswitch service

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerOpenvswitchImage:
    description: image
    default: 'centos-binary-neutron-openvswitch-agent:latest'
    type: string
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  NeutronOvsAgentBase:
    type: ../../puppet/services/neutron-ovs-agent.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for Neutron openvswitch service
    value:
      service_name: {get_attr: [NeutronOvsAgentBase, role_data, service_name]}
      config_settings: {get_attr: [NeutronOvsAgentBase, role_data, config_settings]}
      step_config: {get_attr: [NeutronOvsAgentBase, role_data, step_config]}
      docker_image: &neutron_ovs_agent_image
        list_join:
        - '/'
        - [ {get_param: DockerNamespace}, {get_param: DockerOpenvswitchImage} ]
      puppet_tags: neutron_config,neutron_agent_ovs,neutron_plugin_ml2
      config_volume: neutron
      config_image: *neutron_ovs_agent_image
      kolla_config:
        /var/lib/kolla/config_files/neutron-openvswitch-agent.json:
           command: /usr/bin/neutron-openvswitch-agent --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini --config-file /etc/neutron/plugins/ml2/openvswitch_agent.ini
           config_files:
           - dest: /etc/neutron/neutron.conf
             owner: neutron
             perm: '0600'
             source: /var/lib/kolla/config_files/src/etc/neutron/neutron.conf
           - dest: /etc/neutron/plugins/ml2/ml2_conf.ini
             owner: neutron
             perm: '0600'
             source: /var/lib/kolla/config_files/src/etc/neutron/plugins/ml2/ml2_conf.ini
           - dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
             owner: neutron
             perm: '0600'
             source: /var/lib/kolla/config_files/src/etc/neutron/plugins/ml2/openvswitch_agent.ini
      docker_config:
        step_3:
          neutronovsagent:
            image: *neutron_ovs_agent_image
            net: host
            pid: host
            privileged: true
            restart: always
            volumes:
              - /var/lib/kolla/config_files/neutron-openvswitch-agent.json:/var/lib/kolla/config_files/config.json:ro
              - /var/lib/config-data/neutron_ovs_agent:/var/lib/kolla/config_files/src:ro
              - /etc/localtime:/etc/localtime:ro
              - /lib/modules:/lib/modules:ro
              - /run:/run
              - logs:/var/log/kolla/
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
