heat_template_version: ocata

description: >
  OpenStack containerized Nova Compute service

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerNovaComputeImage:
    description: image
    default: 'centos-binary-nova-compute:latest'
    type: string
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:


  NovaComputeBase:
    type: ../../puppet/services/nova-compute.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Nova Compute service.
    value:
      service_name: {get_attr: [NovaComputeBase, role_data, service_name]}
      config_settings: {get_attr: [NovaComputeBase, role_data, config_settings]}
      step_config: {get_attr: [NovaComputeBase, role_data, step_config]}
      puppet_tags: nova_config,nova_paste_api_ini
      docker_image: &nova_compute_image
        list_join:
        - '/'
        - [ {get_param: DockerNamespace}, {get_param: DockerNovaComputeImage} ]
      config_volume: nova
      config_image: *nova_compute_image
      kolla_config:
        /var/lib/kolla/config_files/nova-compute.json:
           command: /usr/bin/nova-compute
           config_files:
           - dest: /etc/nova/nova.conf
             owner: nova
             perm: '0600'
             source: /var/lib/kolla/config_files/src/etc/nova/nova.conf
           - dest: /etc/nova/rootwrap.conf
             owner: nova
             perm: '0600'
             source: /var/lib/kolla/config_files/src/etc/nova/rootwrap.conf
      docker_config:
        step_4:
          novacompute:
            image: *nova_compute_image
            net: host
            privileged: true
            user: root
            restart: always
            volumes:
              - /var/lib/kolla/config_files/nova-compute.json:/var/lib/kolla/config_files/config.json:ro
              - /var/lib/config-data/nova:/var/lib/kolla/config_files/src:ro
              - /etc/localtime:/etc/localtime:ro
              - /lib/modules:/lib/modules:ro
              - /run:/run
              - /dev:/dev
              - logs:/var/log/kolla/
              - /etc/iscsi:/etc/iscsi
              - libvirtd:/var/lib/libvirt
              - nova_compute:/var/lib/nova/
            environment:
             - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
